Add support for custom network in Google Cloud Life Sciences executor
nextflow-io/nextflow pull request #1810
Opened 2020-11-26 19:49 UTC by hnawar

This pull request adds support for specifying a VPC network to be passed to the Life Sciences API described in issue  #1574

2020-11-27 08:42 UTC, pditommaso requested changes
Hi Hatem, thanks a lot for your time submitting this PR. The only concern I have is that it addresses bot the network name specification *and* the disk type with the introduction of a new diskType directive. 

Regarding the latter, I remember we discussed this in the past and the plan is to add the type as an attribute of the current `disk` directive.  I apologise if still, I haven't made the required changes to accommodate this need, however, I think it would be better to keep this PR only related to the nextflow enhancement.

2020-11-27 08:42 UTC, pditommaso commented on modules/nf-google/src/main/nextflow/cloud/google/lifesciences/GoogleLifeSciencesHelper.groovy
> +        if(req.network!=null | req.usePrivateAddress ) {
I think the condition should `req.network || req.usePrivateAddress` (not null it's evaluated to true by groovy and `|` it's bitwise OR)

2020-12-07 20:30 UTC, pditommaso commented
I guess this PR was closed by mistake. I'm merging it manually the avoid including the Cost file and fixing a typo in the docs. Thanks for contributing!

2020-12-07 20:45 UTC, pditommaso commented
Merged 3563e171

2020-12-08 12:59 UTC, hnawar commented
Hi Paolo,
Please don't merge this PR, I've done some further testing and there are cases that it fails.
I will update you again as it passes.

Hatem

2020-12-08 14:11 UTC, pditommaso commented
I see, need to roll back the merge than

2020-12-28 23:20 UTC, galvinma commented
Hi, was wondering the status of this issue? Is this slated to be rolled out in production soon?

2021-02-04 16:05 UTC, mjpworth commented
I am curious about the state of this feature (specifying a specific network). this is a feature we are also interested in - to comply with our IT security directives. 
Thanks.

2021-02-08 11:06 UTC, pditommaso commented
@hnawar if you can comment about what's missing to this PR and can try to solve it.

2021-02-08 11:34 UTC, hnawar commented
Hi Paolo,
I'm trying to clean up the changes, also I was only updating the network
but not the subnet which caused this to not work properly when manual
subnets are used. I am trying to test the changes, but this is what is
missing
Hatem

On Mon, 8 Feb 2021 at 11:07, Paolo Di Tommaso <notifications@github.com>
wrote:

> @hnawar <https://github.com/hnawar> if you can comment about what's
> missing to this PR and can try to solve it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nextflow-io/nextflow/pull/1810#issuecomment-775064591>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD2HK5MQAWF2YEGX5LS65ELS57AVXANCNFSM4UEDMDTQ>
> .
>

2021-02-08 15:02 UTC, pditommaso commented
I see. don't want to put pressure just let me know if you can do it or if you want me or somebody else to. give a try.

2021-02-08 15:24 UTC, galvinma commented
FWIW I have been using this code for a while to run jobs in a private VPC: https://github.com/nextflow-io/nextflow/pull/1883/files

Only thing missing would be tests around the subnetwork keyword.

2021-02-10 22:21 UTC, pditommaso commented
Solved by 171f4aa8

2021-02-10 22:21 UTC, closed without merging