Append clusterOptions at the beginning of PBS directives
nextflow-io/nextflow pull request #2036
Opened 2021-04-13 12:05 UTC by IdoBar

when multiple competing directives are provided, the first one will take effect, so task.config.clusterOptions should be appended to the beginning of the PBS directives string, not the end of it, see #911

2021-04-15 07:39 UTC, pditommaso commented
Is there docs from PBS vendor regarding this behaviour?

2021-04-17 12:30 UTC, IdoBar commented
According to the [PBSPro 19.2 User Guide](https://www.altair.com/pdfs/pbsworks/PBSUserGuide19.2.3.pdf) (P.69)

> **4.3.8.8  Only One select Statement Per Job**
You can include at most one select statement per job submission.

It doesn't say what happens when you include more than one statement (though I've shown this in #911 and will double-check this on a different HPC cluster running PBS Pro).

2021-04-20 01:04 UTC, IdoBar commented
Yes, can confirm this to be the case on two independent HPC clusters running PBS Pro v19.2.3 (20190726105414) and v18.1.2
```
cat .command.test
#!/bin/bash
#PBS -N nf-test
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=1:mem=6144mb
#PBS -l select=1:ncpus=2:mem=10kb

sleep 30

$ cat .command.test2
#!/bin/bash
#PBS -N nf-test2
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=2:mem=10kb
#PBS -l select=1:ncpus=1:mem=6144mb

sleep 30

$ qsub .command.test
$ qsub .command.test2
$ qstat -u $USER
gc-prd-hpcadm:
                                                            Req'd  Req'd   Elap
Job ID          Username Queue    Jobname    SessID NDS TSK Memory Time  S Time
--------------- -------- -------- ---------- ------ --- --- ------ ----- - -----
100420.gc-prd-h s2978925 workq    nf-test     70894   1   1  6144m 00:30 R 00:00
100421.gc-prd-h s2978925 workq    nf-test2    70983   1   2   10kb 00:30 R 00:00
```

2021-04-20 09:17 UTC, pditommaso requested changes
Ok, thank you. In this case please let's add a more explicit comment explaining the reason why the `clusterOption` has to be the first directive . Also a test check-in that would be useful

2021-04-23 00:47 UTC, IdoBar commented
Where would you like this comment to be? In this PR on in the actual code?
I will also add a suitable test.

2021-04-23 07:37 UTC, pditommaso commented
In the code, thanks!

2021-05-28 20:36 UTC, pditommaso commented
Merged manually 75e3f225. Thanks for contributing.

2021-05-28 20:36 UTC, closed without merging

2021-07-03 20:55 UTC, pditommaso commented
Included in release `21.06.0-edge`.