Fix for nested params with the same name
nextflow-io/nextflow pull request #2485
Opened 2021-12-07 16:44 UTC by jacarey

This fixes both #1982 and #2247

Both cases were caused by a lack of cloning which allowed mutability of values where they should have been immutable.

2021-12-07 18:28 UTC, nh13 approved these changes

2021-12-07 18:28 UTC, nh13 commented on modules/nextflow/src/test/groovy/nextflow/config/ConfigParserTest.groovy
> +    def 'should not overwrite param values with nested values of with the same name' () {
```suggestion
    def 'should not overwrite param values with nested values with the same name' () {
```

2021-12-08 15:39 UTC, pditommaso requested changes
Awesome patch, this was really tricky! 

Find attached a patch to fix also a failing test, plus one more test to check the dotted notation of the same snippet 


[patch.txt](https://github.com/nextflow-io/nextflow/files/7677126/patch.txt)

2021-12-08 22:45 UTC, pditommaso approved these changes
Awesome, thanks

2021-12-08 22:46 UTC, merged

2021-12-22 08:39 UTC, pditommaso commented
Release along with version 21.12.1-edge