Scipio extended error report
nextflow-io/nextflow pull request #2569
Opened 2022-01-18 09:12 UTC by mguinin

Hi, thank you very much for developing nexflow.
At Scipio-bioscience we created this fork because we felt the need to have more precise errors report. For now this fork is meant to be more functional than pretty, it is a work in progress.

Our problem was the lines reported in the error messages didn't always point the exact location where the error happened, but rather the general wrapping scope, furthermore the script names were not human readable (numbers) in the extended error stack in .nextflow.log 

As our nextflow code grow in size we had more and more difficulties to find the new errors, so I created this hack were additional information is appended at the end of the cause chain of the error stack, so we are 100% sure the info is always displayed. Obviously it would be cleaner to move those message outside of the error stack. We are open to any suggestion.

Thanks again,
Mathieu Guinin
Scipio-bioscience
mathieu.guinin@scipio.bio

2022-01-20 13:25 UTC, pditommaso requested changes
Hello, thanks for considering contributing to this project. 

I've left some comments, most of them related to changes related to files automatically modified by the build script. Those changes should not be committed to preventing conflicts during the merge. 

Also, I need more context on the rationale of this PR. How exactly is modifying the error message? Can you provide a script example showing the PR in action?

2022-01-20 13:25 UTC, pditommaso commented on docs/conf.py
This should not be commited

2022-01-20 13:25 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/processor/TaskPollingMonitor.groovy
> +            println("Killing task: " + handler.task.name)
`println` statement should not be used for logging

2022-01-20 13:25 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/script/ExecutionStack.groovy
> +class ERROR_IN_NEXTFLOW_PIPELINE extends Throwable {
The use of all uppercase class names is very unusual for Groovy/Java code convention. Camel case should be used instead

2022-01-20 13:25 UTC, pditommaso commented on modules/nextflow/src/main/resources/META-INF/plugins-info.txt
> +nf-google@1.1.3
This should not be commited

2022-01-20 13:25 UTC, pditommaso commented on modules/nf-commons/src/main/nextflow/Const.groovy
>       * The app build time string relative to UTC timezone
This should not be commited

2022-01-20 13:25 UTC, pditommaso commented on nextflow
>  NXF_ORG=${NXF_ORG:-'nextflow-io'}
This should not be commited

2022-01-20 13:25 UTC, pditommaso commented
Please also review the contributing document https://github.com/nextflow-io/nextflow/blob/master/CONTRIBUTING.md#contributing-to-nextflow

2022-01-21 17:00 UTC, mguinin commented
Thank you for considering my pull request !
I have done the change about the naming convention and remove the unwanted files from commit.


**Here are two examples where the error report is improved:**


1. In the following example the error line in the console point to line 11, the proposed improvement allow to find the root cause of the problem at line 4. Notice that in this example the initCause wrapping is performed in the nextflow code, usually it gets even worse when it happens in groovy code: we frequently got the main workflow opening bracket as the error line. 


```
nextflow.enable.dsl=2

def failTestFunc() {
    throw new Error("this is meant to fail")
}

workflow {
    try {
        failTestFunc()
    } catch (Throwable e) {
        throw new Error("something went wrong").initCause(e)
    }
}
```



2.  In this example nexflow only display the error message, not the full stack. The proposed improvement allow to retrieve the exact error line:

```
nextflow.enable.dsl=2

process failTestProcess {
    input:
        val(x)
    output:
        val(y)

    exec:
        throw new Error("this is meant to fail")
        y=2*x
}

workflow {
    failTestProcess(42)
}
```

2023-02-08 21:11 UTC, pditommaso commented
Closing as outdated

2023-02-08 21:11 UTC, closed without merging