Fix S3 file staging when there are spaces in the filename
nextflow-io/nextflow pull request #2762
Opened 2022-03-30 23:08 UTC by nathanthorpe

Add quotes around the file paths in the `nxf_s3_download` function.

Currently it errors out if it receives a file with a space in it.

Here is an example of what the `nxf_stage` function in `command.run` looks like

```
downloads+=("nxf_s3_download s3://<bucket>/resources/data/references/barcodes/test\ space/barcode.txt barcodes.txt")
```

The command log looks like this after running:

```
nxf-scratch-dir ip-10-0-1-196.us-west-2.compute.internal:/tmp/nxf.GW2vFFIgyN

Unknown options: space/barcode.txt

Unknown options: barcodes.txt
```

2022-04-01 15:44 UTC, sminot commented
This fix would be extremely helpful -- thank you @nathanthorpe!

@pditommaso, I hope that this fix looks good to you

2022-04-01 15:58 UTC, pditommaso commented
It does, what surprises me how this test pass without this patch! 

https://github.com/nextflow-io/nextflow/blob/master/validation/test-complexpaths.nf#L3-L42

2022-04-04 16:37 UTC, pditommaso commented
Fascinating, I'll double-check it

2022-04-05 06:42 UTC, pditommaso commented
It works in my computer 😄 


```
» nextflow run test-complexpaths.nf -c awsbatch.config
N E X T F L O W  ~  version 22.02.1-edge
Launching `test-complexpaths.nf` [awesome_lovelace] - revision: 4bd20072c9
executor >  awsbatch (2)
[3b/bc1406] process > foo [100%] 1 of 1 ✔
[88/2c4358] process > bar [100%] 1 of 1 ✔
Hello world!


» nextflow run test-complexpaths.nf -c awsbatch.config -resume
N E X T F L O W  ~  version 22.02.1-edge
Launching `test-complexpaths.nf` [trusting_hilbert] - revision: 4bd20072c9
[3b/bc1406] process > foo [100%] 1 of 1, cached: 1 ✔
[88/2c4358] process > bar [100%] 1 of 1, cached: 1 ✔
Hello world
```


Kidding apart, it's needed a test that captures current broken behaviour and what this PR fixes.

2022-04-05 06:43 UTC, pditommaso requested changes
as commented above

2022-04-05 20:38 UTC, nathanthorpe commented
I can't seem to reproduce the command.run issue like I was before, but the issue still persists in my nextflow environment. I'll close this until I get more information... seems like it could be related to this https://github.com/aws-samples/aws-genomics-workflows/issues/146. Thanks

2022-04-05 20:38 UTC, closed without merging