Add tolerations pod option
nextflow-io/nextflow pull request #2763
Opened 2022-03-31 01:35 UTC by bentsherman

This PR adds the `tolerations` pod option, which allows a pod to "tolerate" certain node taints during scheduling. Can be useful for situations where a node is designated for a specific use case (special CPU type, belongs to certain user group, etc), so it will only be scheduled to users who specifically tolerate the taint.

I also reorganized some of the pod-related classes to be more readable. I pushed two separate commits so that you can distinguish the toleration-specific changes from the general changes.

2022-04-05 06:31 UTC, pditommaso requested changes
Hi, I think is useful but there are several unrelated changes that make the review difficult. Try to keep the PR as much as possible self-contained. Thanks!

2022-04-05 13:17 UTC, bentsherman commented
I wanted to clean up some of the k8s-related files to make them easier to read, but I wasn't sure if they justified a separate PR, so I included them with this one. You can inspect the two commits separately to make the review easier. Or if you prefer I could make a separate "general k8s cleanup" PR.

2022-04-07 19:54 UTC, bentsherman commented
Okay I moved the k8s cleanup to a separate draft PR for later. Now you should only see the feature-specific changes.

2022-04-10 07:17 UTC, pditommaso approved these changes
Ok, nice 👍

2022-04-10 07:18 UTC, merged