Add MaxErrorRetry to k8s-config (replace hardcoded 5 maxRetry)
nextflow-io/nextflow pull request #2957
Opened 2022-06-14 01:22 UTC by naineshmp

2022-07-25 13:46 UTC, bentsherman commented
Thanks for your contribution. I think the option should be called something like `maxRequestRetries` so that it is clearly distinguished from `maxRetries` directive for retrying tasks. This option is about K8s API calls. Also, if you would please document this option in `config.rst`, under the `k8s` config scope.

2022-08-17 11:42 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/k8s/client/ClientConfig.groovy
> +    Integer maxErrorRetry
```suggestion
    Integer maxErrorRetry = 5
```

2022-08-17 11:43 UTC, pditommaso requested changes
Ok nice. A test should be added to verify that setting is read from the config, otherwise it should default to 5

2022-08-17 23:15 UTC, naineshmp commented
> Ok nice. A test should be added to verify that setting is read from the config, otherwise it should default to 5

Thanks for your review. Let me make the change.

2022-08-18 03:18 UTC, naineshmp commented
> Ok nice. A test should be added to verify that setting is read from the config, otherwise it should default to 5

I have completed the change, could you please review? Thanks.

2022-08-18 10:54 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/k8s/client/ClientConfig.groovy
> +    Integer maxErrorRetry = 5
Checking better think this is useless. The client config is used to discover the K8s config in the HOME/.kube/config path. 

Instead this should go in the [K8sConfig](https://github.com/nextflow-io/nextflow/blob/979e39fd0a5e87b1d57918a424382e35d2af1951/modules/nextflow/src/main/groovy/nextflow/k8s/K8sConfig.groovy#L75-L75), tho is not easy then to access it from the client

2022-08-18 12:47 UTC, bentsherman commented on docs/config.rst
> +maxRequestRetries   Defines the Kubernetes API max request retries (default is set to 5)
Can we name this `maxErrorRetry` as well so that it's consistent with the analogous options for HPC and Azure?

2022-09-21 20:17 UTC, pditommaso commented
Merge manually 👉  a6155943. @bentsherman I've accommodated your request adjusting the check considering the different semantics of attempt vs retry

2022-09-21 20:17 UTC, closed without merging