update of Scripts `à la carte`
nextflow-io/nextflow pull request #3535
Opened 2023-01-07 19:25 UTC by nick-youngblut

Provided explicit examples of using input values & paths in a la carte scripts.

Signed-off-by: Nick Youngblut <nyoungb2@gmail.com>

2023-01-09 03:31 UTC, mribeirodantas requested changes
For beginners, this can be slightly difficult to read so I would suggest to add a comment, such as this one.

2023-01-09 03:31 UTC, mribeirodantas commented on docs/process.rst
> +
```suggestion
        // Reads the content of a file, and writes it to `table.txt`
```

2023-01-09 03:36 UTC, mribeirodantas approved these changes

2023-01-24 20:25 UTC, mribeirodantas requested changes

2023-01-24 20:25 UTC, mribeirodantas commented on docs/process.rst
> +        // Reads the content of a file, and writes it to `table.txt`
```suggestion
        # Reads the content of a file, and writes it to `table.txt`
```

It's Python now, not Groovy/Nextflow so we should use the appropriate comment symbol.

2023-01-24 20:55 UTC, mribeirodantas requested changes

2023-01-24 20:55 UTC, mribeirodantas commented on docs/process.rst
> +        val(x)
```suggestion
        val(x)
        output:
        stdout
```

2023-01-24 20:55 UTC, mribeirodantas commented on docs/process.rst
> +        path(x)
```suggestion
        path(x)
        output:
        stdout
```

2023-01-25 05:07 UTC, mribeirodantas approved these changes

2023-02-12 16:20 UTC, pditommaso commented
Hi, sorry for the late reply. The goal of the example is to show how to invoke other interpreters via the shebang declaration. 

For this reason, I think it's better to add input and keep the example self-contained. Changed  it to add the workflow invocation 6d6b3543

2023-02-12 16:20 UTC, closed without merging

2023-02-16 15:46 UTC, nick-youngblut commented
@pditommaso if the goal of this example was to:

>show how to invoke other interpreters via the shebang declaration

...then maybe including a separate example in the docs of how to actually write python/perl code using shell variable interpretation (as in this PR) would be helpful?

2023-02-17 08:58 UTC, pditommaso commented
Likely. The key thing it's not going to be a Shell variable, but it should use the syntax of the target scripting language ie. python/perl/R etc. I think this is what confuses people