Use separate script for long stage/unstage commands
nextflow-io/nextflow pull request #3851
Opened 2023-04-11 16:42 UTC by bentsherman

Closes #2852 

TODO:
- [ ] e2e test

2023-04-11 19:36 UTC, bentsherman commented
CI tests were double triggered for push and pull_request, @ewels did we do something wrong?

2023-04-11 19:38 UTC, ewels commented
It's because your fork is out of date. I think if you hit "Update branch" it should work as expected... 🤞🏻

2023-04-11 21:23 UTC, ewels commented
Sorry, couldn't resist hitting the button to find out 😆

Looking good now though!

2023-04-12 14:48 UTC, bentsherman commented
Looking at #2118 , I believe this check was added as a partial solution: https://github.com/nextflow-io/nextflow/blob/6ef14c00c1d72ad5313d3c6ffa1ce2f9ab4f275d/modules/nextflow/src/main/groovy/nextflow/executor/SimpleFileCopyStrategy.groovy#L132-L133

So can we safely remove this check? Now it will be in the `.command.stage` script anyway.

2023-04-13 20:17 UTC, pditommaso requested changes

2023-04-13 20:17 UTC, pditommaso commented on modules/nextflow/src/main/resources/nextflow/executor/command-stage.txt
This template is not needed. It's enough to write the staging script to a file

2023-04-13 20:17 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy
> +        inputFiles.size() >= 1000
Worth to parametrise this with an env var, and use it to create a unit test with a few number for files

2023-04-18 05:34 UTC, pditommaso commented
Made some improvements: 
- write files using newBufferedWriter to avoid allocation a new `byte[]` buffer that for large file can be expensive 
- use `bash` instead of `source` to read the stage command 
- use `NXF_WRAPPER_STAGE_FILE_THRESHOLD` as bytes threshold instead of num of files to better control it

2023-04-18 14:22 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/executor/SimpleFileCopyStrategy.groovy
> -            // link them
I'd keep this, to avoid stressing the storage with thousands of unneeded `rm`s

2023-04-18 14:44 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/executor/SimpleFileCopyStrategy.groovy
> -            // link them
how this has been solved? 😅

2023-04-18 15:18 UTC, pditommaso commented on tests/checks/stage-file.nf/.checks
Worth adding a second run with resume and verify it works as expected

2023-04-19 07:02 UTC, pditommaso commented
Considering the Slurm limit is 5MB (see [here](https://github.com/nextflow-io/nextflow/issues/2118)), i've creased the default to 1 MB

2023-04-19 07:31 UTC, pditommaso commented
Let's merge this. Solve #2852

2023-04-19 07:31 UTC, merged

2023-04-19 07:43 UTC, ewels commented
![](https://media.giphy.com/media/mZSgBvMch06btpJHCE/giphy-downsized.gif)