Add CPU model name to trace files and traceRecord
nextflow-io/nextflow pull request #3946
Opened 2023-05-15 11:35 UTC by skrakau

This adds the CPU model name to the trace files (to allow using this information for a CO2 footprint plugin) and accordingly to the `traceRecord`.

It is not added to any tests yet.

2023-05-15 12:58 UTC, bentsherman commented
Wondering if we should integrate this with the `arch` directive somehow. See #3786

2023-05-25 20:34 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/trace/TraceRecord.groovy
> +            cpu_model:  'str',      // -- /proc/cpuinfo field 'model name'
Let's add this at the bottom of the list, after `hostname`

2023-05-25 20:37 UTC, pditommaso commented
I would expect the `arch` to be included in the CPU model

2023-05-25 21:38 UTC, pditommaso requested changes
This looks ok, but there's a failing test. Likey due to new field

2023-06-20 13:18 UTC, skrakau commented
Hi, 
I moved the new `cpu_model` field to the end of the list, adjusted the `test-bash-wrapper-with-trace.txt` file to the new `command-trace.txt` since this caused an error in the `BashWrapperBuilderTest` test, and added an entry to the docs. I hope I didn't forget anything.

2023-07-05 08:34 UTC, pditommaso commented on docs/tracing.md
> +: The name of the CPU model which was used to execute the task. This data is read from file `/proc/cpuinfo`.
```suggestion
`cpu_model`
: :::{versionadded} 22.07.0-edge
  :::
: The name of the CPU model used to execute the task. This data is read from file `/proc/cpuinfo`.
```

2023-07-05 08:35 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/trace/TraceRecord.groovy
> +            cpu_model:  'str',      // -- /proc/cpuinfo field 'model name'
```suggestion
            cpu_model:  'str'
```

2023-07-05 08:54 UTC, pditommaso approved these changes

2023-07-05 08:55 UTC, pditommaso commented
We are ready to go! Thanks for this useful contribution!

2023-07-05 08:57 UTC, merged

2023-07-05 12:11 UTC, skrakau commented
Thanks for adding it!