Add rule to build Nextflow docker image for ARM
nextflow-io/nextflow pull request #4020
Opened 2023-06-13 21:27 UTC by bentsherman

Close #2750 

Haven't tested it myself, just drafting a PR for anyone who wants to try a Nextflow docker image on ARM:
```bash
cd docker
make build-arm
```

2023-06-14 08:10 UTC, mribeirodantas requested changes
The Dockerfile remains with the target platform set [by default] to amd64. With this change, I was able to create the container image in my machine (Apple M1).

2023-06-14 08:10 UTC, mribeirodantas commented on docker/Makefile
> +	docker buildx build --platform linux/arm64 --output=type=docker --progress=plain --tag nextflow/nextflow:${version} .
```suggestion
	docker buildx build --platform linux/arm64 --output=type=docker --progress=plain --tag nextflow/nextflow:${version} --build-arg TARGETPLATFORM=linux/arm64 .
```

2023-06-14 15:27 UTC, mribeirodantas commented on docker/Makefile
> +	docker buildx build --platform linux/arm64 --output=type=docker --progress=plain --tag nextflow/nextflow:${version} .
Yeah! 🥳

<img width="272" alt="CleanShot 2023-06-14 at 17 27 09@2x" src="https://github.com/nextflow-io/nextflow/assets/1023197/d91feccc-a989-4a7c-bdf9-3f5aa256297c">

No warning about architecture 🤩

2023-06-15 00:38 UTC, mribeirodantas commented on docker/Makefile
> +	docker buildx build --platform linux/arm64 --output=type=docker --progress=plain --tag nextflow/nextflow:${version} .
Sure.

<img width="716" alt="CleanShot 2023-06-15 at 02 37 45@2x" src="https://github.com/nextflow-io/nextflow/assets/1023197/a2bcfac4-aa62-41fc-b6fc-e84886920343">

<img width="1108" alt="CleanShot 2023-06-15 at 02 37 03@2x" src="https://github.com/nextflow-io/nextflow/assets/1023197/ed66077e-2a1c-48a6-803d-d8e3f9288de6">

2023-06-16 09:12 UTC, mribeirodantas approved these changes

2023-06-29 15:04 UTC, bentsherman commented on docker/Makefile
>  	docker buildx build --platform linux/amd64 --output=type=docker --progress=plain --tag nextflow/nextflow:${version} .
Sure, that is the default in the Dockerfile but the consistency is nice

2023-06-29 15:06 UTC, pditommaso approved these changes

2023-06-29 15:06 UTC, merged