Add deleteTasksOnCompletion to Azure task configuration
nextflow-io/nextflow pull request #4114
Opened 2023-07-19 15:46 UTC by adamrtalbot

Deleting Azure Tasks was checking the configuration object
deleteJobsOnCompletion which was incorrect since a task belongs to a
job. This adds the equivalent configuration for tasks which is checked
before deleting the tasks.

Hi! Thanks for contributing to Nextflow project.

When submitting a Pull Request please make sure to not include
in the changeset any modification in these files:

* `nextflow`
* `docs/conf.py`
* `modules/nf-commons/src/main/nextflow/Const.groovy`

Also, please sign-off the DCO [1] to certify you are the author of the contribution
and you adhere to Nextflow open source license [2] adding a `Signed-off-by` line to
the contribution commit message. For more details check [3].

1. https://developercertificate.org/
2. https://github.com/nextflow-io/nextflow/blob/master/COPYING
3. https://github.com/apps/dco

2023-07-20 07:50 UTC, pditommaso requested changes
Ok, tho cleanup logic is becoming a bit convoluted.

2023-07-20 07:50 UTC, pditommaso commented on modules/nf-commons/src/main/nextflow/Const.groovy
Do not include this file in the PR, please

2023-07-20 20:52 UTC, pditommaso commented on plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchTaskHandler.groovy
> -        executor.config.batch().deleteJobsOnCompletion
Why `deleteJobsOnCompletion` is gone?

2023-07-21 12:23 UTC, pditommaso commented
Tagging @bentsherman for reviewing

2023-07-21 15:34 UTC, bentsherman reviewed
Adam, do you think it would be better to remove the task deletion logic? If they are already deleted when the job is deleted (for which there is already a config option), then it seems like that would be better by reducing the number of API calls to Azure Batch. On the other hand, I suppose the tasks would be deleted only when the entire job queue is done, rather than immediately. I'm not sure whether that matters.

2023-07-21 15:35 UTC, bentsherman commented on docs/config.md
> +: Delete tasks after successful completion. This deletes them on the Azure Batch service but files and resources may persist on the compute nodes (default: `true`).
I think you are right, all of these delete flags are false by default.

2023-07-21 15:49 UTC, bentsherman commented
From the [documentation](https://learn.microsoft.com/en-us/rest/api/batchservice/task/delete?tabs=HTTP):

> When a Task is deleted, all of the files in its directory on the Compute Node where it ran are also deleted (regardless of the retention time).

That makes me think there is an advantage to deleting tasks as soon as possible. Unless someone wants to be able to control task deletion and job deletion, I am fine with the current behavior, which controls both via `deleteJobsOnCompletion`.

2023-07-21 15:52 UTC, bentsherman commented
On the other hand, [Dave on StackOverflow](https://stackoverflow.com/questions/34618115/is-deleting-tasks-and-pools-necessary-in-azure-batch-jobs) says:

> You don't need to delete tasks or their jobs at all and there's no real downside of leaving them in the system. You do however need to terminate jobs on completion as there is a quota on the number of active jobs within a Batch account.

I think I will go with the Microsoft docs 😆

2023-07-21 16:09 UTC, bentsherman commented on docs/config.md
> +: Delete tasks after successful completion. This deletes them on the Azure Batch service but files and resources may persist on the compute nodes (default: `true`).
Actually it defaults to false there too:

https://github.com/nextflow-io/nextflow/blob/9fc1d3bd951b1d9d75ba8e64a5aa497cc087f62c/plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchTaskHandler.groovy#L137-L138

2023-07-21 16:09 UTC, bentsherman commented on docs/config.md
> +: Delete tasks after successful completion. This deletes them on the Azure Batch service but files and resources may persist on the compute nodes (default: `true`).
Probably this logic should happen in `AzBatchOpts`

2023-07-21 16:17 UTC, bentsherman commented
But my point is, if the tasks aren't deleted until the entire job is done, will that cause the task files on the VM to accumulate and run out of storage? Or are the task files already deleted some other way?

2023-07-21 16:35 UTC, bentsherman commented
Okay, then let's add your config option making it true by default, and if a user has rate limit issues then they have that option as a lever. Let me push a few minor changes first.

2023-07-21 16:50 UTC, bentsherman commented
The way it works currently is that `deleteTasksOnCompletion` can be true, false, or null. It is true by default, but failed tasks are deleted only if it is *explicitly* true. It's like a hidden third state. So by default, successful tasks will be deleted and failed tasks will be preserved in case you want to inspect it. I think that comment is backwards, so I changed it to "preserve failed tasks for debugging purposes".

If you think that isn't useful, I would be fine with removing it, thereby deleting all tasks by default.

2023-07-21 18:13 UTC, bentsherman commented on docs/config.md
> +: When the workflow completes, set all jobs to complete on task completion. (default: `true`).
Did you mean "terminate" or are they interchangeable?

```suggestion
: When the workflow completes, set all jobs to terminate on task completion. (default: `true`).
```

2023-07-21 18:14 UTC, bentsherman commented on docs/config.md
> +: Delete all jobs when the workflow completes (default: `true`).
```suggestion
: Delete all jobs when the workflow completes (default: `false`).
```

2023-07-24 15:45 UTC, bentsherman commented
Okay I updated the tests and docs to reflect that `deleteJobsOnCompletion` is now false by default. But we should still make `deleteTasksOnCompletion` true by default right? So that we are still deleting the task files from the VMs as soon as possible?

2023-07-25 08:19 UTC, pditommaso approved these changes

2023-07-25 08:20 UTC, merged