Add OCI-mode like for Apptainer
nextflow-io/nextflow pull request #4548
Opened 2023-12-01 04:10 UTC by pditommaso

Add the ability to run OCI containers with Apptainer without the need to convert them explicitly via [ApptainerCache](https://github.com/nextflow-io/nextflow/blob/e9aa8b223ebc1eba9d3627d69f93446fa3004965/modules/nextflow/src/main/groovy/nextflow/container/ApptainerCache.groovy#L28-L28)

2023-12-01 04:51 UTC, marcodelapierre commented
Hold on, see my thread on the originating issue: https://github.com/nextflow-io/nextflow/issues/4543

2023-12-11 15:27 UTC, pditommaso commented
To summarise, currently this PR allows the use of OCI (Docker) containers converting implicitly to SIF image file format both for Singularity and Apptainer by adding respectively the option 

```
singularity.direct = true
apptainer.direct = true
```

Along with this is also supported the native OCI support in singularity 4 by using 

```
singularity.oci = true
```

However, considering they are both OCI containers may a better naming could be 

```
apptainer.autoOciMode = true|false
singularity.autoOciMode = true|false
```

and 

```
singularity.nativeOciMode = true|false
```


OR 

```
apptainer.ociAuto = true|false
singularity.ociAuto = true|false
```

and 

```
singularity.ociNative = true|false
```

2023-12-11 15:56 UTC, marcodelapierre commented
Yep, second 100% your summary around the proposed functionalities.  
Personally, I like `ociAuto` and `ociNative`, as they are concise.  
Also, not that `ociNative` in Singularity implies `ociAuto`.

I will review this PR on Wed at the latest.

2023-12-13 09:52 UTC, marcodelapierre requested changes
A few small requests along the code - thanks Paolo!

2023-12-13 09:52 UTC, marcodelapierre commented on plugins/nf-wave/src/main/io/seqera/wave/plugin/resolver/WaveContainerResolver.groovy
> -        final singularitySpec = freeze && engine in SINGULARITY_LIKE && !singularityOciMode
OK, I see  that SingularitySpec controls whether a Singularityfile or Dockerfile is used. 
At this stage it is not clear to me why this is conditional to `canRunOciImage` being false; though this is not in scope for this PR.

2023-12-13 12:54 UTC, marcodelapierre commented
Forgot to mention: these updates to Oci options need to be reflected in the `docs` as well

2023-12-17 18:40 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/container/ContainerHandler.groovy
> +            if( normalizedImageName.startsWith('docker://') && config.canRunOciImage() )
> I think we can disable image caching in the work dir also in the case of normalized

Don't know. Let's keep for a following iteration

2023-12-17 18:43 UTC, pditommaso commented
Ok, considering the term *OCI native* is used is several places with different meaning, I went for `ociMode` (that's how it's [referred in the docs](https://docs.sylabs.io/guides/latest/user-guide/oci_runtime.html#oci-mode-oci)) and `ociAutoPull`. 

The docs has been updated correspondingly.

2023-12-17 20:12 UTC, merged