Add custom config parser
nextflow-io/nextflow pull request #4744
Opened 2024-02-14 22:27 UTC by bentsherman

Close #2723 

This PR explores one possible solution to the config overhaul by implementing a custom parser for config files, using a similar approach as #4613.

The linked issue initially proposed adopting a new config format. However, most of the proposed alternatives do not have all of the capabilities that we need out of the box or have their own downsides. I think the actual problem is that the config file has been stretched to cover use cases for which it wasn't originally designed.

Between this PR, the module config (#4510), and moving the params definition from the config file to the params schema, I think this will relieve enough pressure from the config file that we can keep it.

This custom parser enforces a much simpler syntax:
- Only three statements are allowed: assignments, blocks, and config inclusion.
- The left-hand side of an assignment can only be a path expression (`foo.bar.baz ...`).
- The right-hand side can be an arbitrary expression, including closures.
- Within a closure expression, arbitrary Groovy code is still allowed, although right now there is only a minimal subset in the parser.

As a result, the config parser is much simpler and the code is easier to read. There is no more dependence on metaclasses, instead there is a simple builder DSL for executing a config file and producing a map.

The vast majority of existing configuration is still supported, with only a few minor changes needed:

- Include statements are sometimes wrapped in a try-catch to prevent a missing config file from failing the pipeline. For this we can either provide both `includeConfig` and `requireConfig`, or demote the error to a warning when the config file is remote

- Custom functions like `check_max` are no longer supported. Instead, I suggest that we import the `lib` directory into config files as we do for scripts, so that these helper functions can simply be defined there

- Conditional statements are no longer supported. With module config they should no longer be needed

- Params should be defined only in `nextflow_schema.json` to prevent issues like #2662 where a param is referenced before params are fully resolved. More of a best practice than a hard requirement. We can still support params defined in the config (likely with a warning), and overriding param default values in a profile is still a valid use case.

All of these issues can be resolved independently of this PR, in case we need to smooth the migration process.

It is still possible to execute arbitrary code with side effects, just not as easily as before. We can't really avoid this if we want to support dynamic expressions:
```groovy
foo.bar = "${println 'pwned'}"
```

TODO:
- [ ] fix build system (Gradle + ANTLR)
- [ ] why aren't block comments working?
- [ ] add custom lazy resolution of params
- [ ] review subset of Groovy that is supported within closures
- [ ] support `lib` directory for using helper functions in config files

2024-03-05 09:03 UTC, bentsherman commented
Research updates:
- Groovy compiler provides an interface to use a custom parser (in order to ease the transition from Antlr2 to Antlr4), this can be used to inject our custom parser without much hassle
- Config schema effort can be pursued independently of the parser, see #4201 
- Might be able to use the [Java security manager](https://docs.oracle.com/javase/8/docs/api/java/lang/SecurityManager.html) to prevent execution of unsafe code in the config file such as file I/O, subprocesses

2024-03-08 05:35 UTC, bentsherman commented
Here's an example to illustrate how the config parser "executes" the config file. Given this config:
```groovy
foo.bar = 'hello'

foo {
  bar = 'hello'
}

includeConfig 'foobar.config'
```

The parser transforms this code into the following:
```groovy
assign(['foo', 'bar'], 'hello')

block('foo', {
  assign(['bar'], 'hello')
}

includeConfig('foobar.config')
```

Basically each statement is translated to a DSL method (see `ConfigDsl`). This "hidden DSL" allows us to control how each statement is executed. In other words, the config parser + hidden DSL implement a simple interpreter for the Nextflow config language, separating the config language from the config execution.

I think this is a good model for how we might separate the Nextflow language from the runtime. Instead of hooking directly into Groovy methods and relying on Groovy MOP, metaclass, etc, we can introduce a hidden DSL which allows us to better control how a given statement (e.g. invoking a process in a workflow) is executed by the runtime.

2024-03-11 13:13 UTC, bentsherman commented
Java security manager is being [removed](https://snyk.io/blog/securitymanager-removed-java/). I will keep an eye out for other sandboxing techniques, but in the meantime, a simple solution is to provide a "safe" execution mode where assignment expressions are wrapped in string literals.

2024-04-07 07:44 UTC, ewels commented
Really like the way that this is going, great work 👏🏻

2024-06-11 12:12 UTC, pditommaso commented
@bentsherman can you please solve the conflicts?

2024-06-11 13:43 UTC, bentsherman commented
The PR I wanted you to review is this one -- #4201 

However I just looked at it and it's not really in a review-able state. I'll ping you again when it's more complete.

2025-01-29 22:15 UTC, bentsherman commented
Trying to get jitpack to work. So far I can build with mavenLocal but not with jitpack.

- Language server PR: https://github.com/nextflow-io/language-server/pull/95
- Following the jitpack docs [here](https://docs.jitpack.io/) and [here](https://docs.jitpack.io/building/).

I had to move all of the repositories config to settings.gradle and add this setting for jitpack: https://github.com/nextflow-io/nextflow/blob/a4cbea481a89abb0655925d0b3f7a5de6949a90c/settings.gradle#L35-L38

Then I would specify the dependency like this:
```groovy
    implementation 'com.github.nextflow-io:language-server:compiler:jitpack-SNAPSHOT'
```

But it doesn't even seem to use the jitpack repository. It just searches the other ones and fails.

I can pull from mavenLocal like this:
```groovy
    implementation 'com.github.nextflow-io:compiler:jitpack-SNAPSHOT'
```

So I have updated the CI to do this for now since it is slightly better. But I might need some help to get the jitpack to work.

2025-01-30 15:19 UTC, pditommaso commented on build.gradle
> -
This should not be removed instead `	maven { url 'https://jitpack.io' }` should be added

2025-01-30 17:06 UTC, bentsherman commented on build.gradle
> -
I had to move all of the repositories config to `settings.gradle` because the `dependencyResolutionManagement` recommended by jitpack was not recognized here

2025-01-30 17:08 UTC, pditommaso commented on build.gradle
> -
It should be enough adding `maven { url 'https://jitpack.io' }` here and nothing else

2025-01-30 17:19 UTC, bentsherman commented on build.gradle
> -
Turns out the includeGroup for jitpack was too strict. Local build is now working with jitpack. I will now see if I can move the config back into the build.gradle

2025-02-15 16:02 UTC, bentsherman commented
@pditommaso config parser is ready to review

Also, this google test is failing again. Do the credentials need to be refreshed?

```
BatchLoggingTest > should fetch logs FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at BatchLoggingTest.groovy:149
```

2025-02-18 15:54 UTC, bentsherman commented on modules/nextflow/src/test/groovy/nextflow/config/parser/legacy/ConfigParserLegacyTest.groovy
> +    def 'should apply profiles in the order they were defined' () {
@pditommaso this test is related to #1792 . We determined that config profiles are applied this way with the legacy parser. We could patch it, but I figure there's no point now, so just added a test to verify it's behavior.

2025-02-18 18:53 UTC, bentsherman commented
@pditommaso tests are passing, let's review and merge

2025-02-19 06:58 UTC, christopher-hakkaart commented on docs/updating-syntax.md
> +The strict config syntax can be enabled in Nextflow by setting `NXF_ENABLE_STRICT_SYNTAX=true`.
```suggestion
Enable the strict config syntax by setting `NXF_ENABLE_STRICT_SYNTAX=true`.
```
I wonder if this should be worded actively as the rest of the section relies on this being set. Don't consider this a blocker if you disagree.

2025-02-19 15:19 UTC, pditommaso requested changes

2025-02-19 15:19 UTC, pditommaso commented on .github/workflows/build.yml
> +        strict_syntax: [true, false]
This results in too many builds. I was suggesting to add it as a `test_mode` then hook in the test.sh script and run `test_integration` using the new parser

2025-02-19 15:19 UTC, pditommaso commented on docs/reference/env-vars.md
> +`NXF_ENABLE_STRICT_SYNTAX`
```suggestion
`NXF_ENABLE_SYNTAX_PARSER_V2` (?)
```

2025-02-19 15:19 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/config/ConfigParserFactory.groovy
> + * @author Ben Sherman <bentshermann@gmail.com>
Add a description please

2025-02-19 15:19 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/config/parser/ConfigToGroovyVisitor.java
> + *
Add a description please

2025-02-19 15:19 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/config/parser/legacy/ConfigBase.groovy
> +package nextflow.config.parser.legacy
it would be preferable to not shuffle stuff around and use `Legacy`.

2025-02-19 15:19 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/config/parser/legacy/ConfigParserLegacy.groovy
Consider keep current naming and use `ConfigParserV2` for the new one

2025-02-19 19:15 UTC, bentsherman commented on docs/updating-syntax.md
> +The strict config syntax can be enabled in Nextflow by setting `NXF_ENABLE_STRICT_SYNTAX=true`.
Yeah, I prefer this wording because the user might follow these migration notes with the language server or with Nextflow 25.04, so it's not essential that they enable this variable

2025-02-19 19:17 UTC, bentsherman commented on .github/workflows/build.yml
> +        strict_syntax: [true, false]
That makes more sense. I didn't want to double the number of builds either

2025-02-19 19:21 UTC, bentsherman commented on docs/reference/env-vars.md
> +`NXF_ENABLE_STRICT_SYNTAX`
Well, I think it will be better to call it `NXF_ENABLE_STRICT_SYNTAX` to keep consistent with our terminology around [strict syntax](https://nextflow.io/docs/latest/updating-syntax.html#preparing-for-strict-syntax). It's not just a new and improved parser, it's a formal language spec.

2025-02-19 19:22 UTC, bentsherman commented on modules/nextflow/src/main/groovy/nextflow/config/parser/legacy/ConfigParserLegacy.groovy
`ConfigParser` now refers to the shared interface which both parsers implement. That's why I had to rename them. I could call them `ConfigParserV1` and `ConfigParserV2`.

2025-02-19 19:25 UTC, bentsherman commented on modules/nextflow/src/main/groovy/nextflow/config/parser/legacy/ConfigBase.groovy
> +package nextflow.config.parser.legacy
I think this is a reasonable change to keep related classes organized. You have done a similar thing many times, e.g. `nextflow.executor.local` or your proposed operator cleanup for the provenance tracking

2025-02-20 08:07 UTC, christopher-hakkaart commented on docs/updating-syntax.md
> +The strict config syntax can be enabled in Nextflow by setting `NXF_ENABLE_STRICT_SYNTAX=true`.
Valid - all good 👍 Thanks!

2025-02-20 08:19 UTC, christopher-hakkaart approved these changes
One minor suggestion but otherwise the docs look great.

2025-02-20 08:19 UTC, christopher-hakkaart commented on docs/config.md
> +This configuration defines three profiles: `standard`, `cluster`, and `cloud`. Each profile provides a different configuration for a given execution environment. The `standard` profile is used by def
```suggestion
The above configuration defines three profiles: `standard`, `cluster`, and `cloud`. Each profile provides a different configuration for a given execution environment. The `standard` profile is used by default when no profile is specified.
```

2025-02-20 14:33 UTC, bentsherman commented
Another flaky CI test:

```
~ Test 'publish-s3-kms.nf' run failed
   + /home/runner/work/nextflow/nextflow/nextflow -q run ../../publish-s3-kms.nf -c .config
   ++ check_kms_key
   ++ aws s3api head-object --bucket nf-kms-xyz --key work/ci-test/publish-s3/HELLO.tsv
   ++ grep -c e5109f93-b42d-4c26-89ee-8b251029a41d
   
   An error occurred (404) when calling the HeadObject operation: Not Found
```

2025-02-24 13:05 UTC, bentsherman commented on docs/reference/env-vars.md
> +`NXF_ENABLE_STRICT_SYNTAX`
The strict feature flag won't be needed as we continue with the strict language spec, so I would rather just phase it out than try to work around it.

2025-02-24 20:44 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/config/parser/legacy/ConfigBase.groovy
> +package nextflow.config.parser.legacy
That's fair, what I think it should be avoid the use of the term "legacy" in class or package name, as it's a bad practice to use the term "new" when introducing new class. It would be preferable just to use `v1` for current ones and v2 for new ones.

2025-02-25 17:22 UTC, merged