In Google Batch, support user specified boot images
nextflow-io/nextflow pull request #5268
Opened 2024-08-30 18:41 UTC by siddharthab

2024-09-02 08:16 UTC, pditommaso requested changes
Thanks for this PR. It would be useful to add some unit tests to validate the changes

2024-09-02 20:51 UTC, siddharthab commented
> Thanks for this PR. It would be useful to add some unit tests to validate the changes

Added a very basic unit test; tested with `./gradlew ':plugins:nf-google:test'`. Please let me know if you would like more.

2024-09-03 07:30 UTC, pditommaso approved these changes
all fine. thanks for this contribution

2024-09-03 07:32 UTC, merged

2024-09-03 15:39 UTC, bentsherman commented
@siddharthab do you know if the boot image can be specified in an instance template? if so, we should add a warning that the boot image option you added will be overridden by the instance template if one is used:

https://github.com/nextflow-io/nextflow/blob/bf0cd326572eea34cb32dbd26f94ed7fc9faed6a/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy#L299-L318

2024-09-03 16:26 UTC, siddharthab commented
> if so, we should add a warning

You are right. I missed the warnings section. Will send another PR.