Add hybrid workflow documentation for Azure
nextflow-io/nextflow pull request #5361
Opened 2024-10-03 16:57 UTC by adamrtalbot

Signed-off-by: adamrtalbot <12817534+adamrtalbot@users.noreply.github.com>

Hi! Thanks for contributing to Nextflow project.

When submitting a Pull Request please make sure to not include
in the changeset any modification in these files:

* `nextflow`
* `modules/nf-commons/src/main/nextflow/Const.groovy`

Also, please sign-off the DCO [1] to certify you are the author of the contribution
and you adhere to Nextflow open source license [2] adding a `Signed-off-by` line to
the contribution commit message. For more details check [3].

1. https://developercertificate.org/
2. https://github.com/nextflow-io/nextflow/blob/master/COPYING
3. https://github.com/apps/dco

2024-10-03 17:24 UTC, pditommaso approved these changes

2024-10-03 17:26 UTC, pditommaso requested changes
Let's mention that's not needed for Fusion and link the Fusion docs https://www.nextflow.io/docs/latest/fusion.html#azure-cloud

2024-10-04 05:50 UTC, christopher-hakkaart commented on docs/azure.md
> +To enable this feature, use one or more {ref}`config-process-selectors` in your Nextflow configuration to apply the Azure Batch configuration to the subset of processes that you want to offload. For
```suggestion
Nextflow allows the use of multiple executors in the same workflow application. This feature lets you deploy hybrid workloads, where some jobs run on the local computer or local computing cluster, while others are offloaded to Azure Batch.

To enable this feature, you configure one or more {ref}`config-process-selectors` in your Nextflow configuration to apply the Azure Batch settings to the processes you want to offload. For example:
```
Changing to present tense

2024-10-04 05:50 UTC, christopher-hakkaart commented on docs/azure.md
> +Then launch the pipeline with the `-bucket-dir` option to specify an Azure Blob Storage path for the jobs computed with Azure Batch and, optionally, the `-work-dir` to specify the local storage for t
```suggestion
With the above configuration, processes with the bigTask {ref}`process-label` run on Azure Batch, while the remaining processes run on the local computer.

Next, launch the pipeline with the `-bucket-dir` option to specify an Azure Blob Storage path for the jobs running on Azure Batch, and optionally, use the `-work-dir` option to specify local storage for the jobs running locally:
```
Making present tense

2024-10-11 12:30 UTC, pditommaso commented
It would be nice to address [this](https://github.com/nextflow-io/nextflow/pull/5361#pullrequestreview-2346254984) to merge it

2024-10-14 09:29 UTC, pditommaso commented on docs/azure.md
> +:::{note}
```suggestion
:::{tip}
```

2024-10-14 09:30 UTC, pditommaso commented
Nice!

2024-10-14 09:30 UTC, merged