Mitigate Interrupted system call on trace_file writes
nextflow-io/nextflow pull request #5397
Opened 2024-10-11 16:31 UTC by infinite-turtles

Writes to files from bash built-ins like `echo` can be fallible, particularly in older versions of bash, such as versions 4.2.x and 4.4.x. This often lead to errors when running numerous processes with tracing enabled on network-based file systems, such as:

`.command.run: line 172: echo: write error: Interrupted system call`

Here is a potential mitigation. To address this, `echo` commands were consolidated into a single block to write to `$trace_file` with an error message on failure. This is assuming that the lack of a .command.trace file will not cause any downstream failures.

### Reference
For more details on similar issues, see: https://unix.stackexchange.com/a/487260

Signed-off-by: Nico Holguin <nholguin@illumina.com>

2024-11-21 08:25 UTC, jorgee requested changes

2024-12-02 19:54 UTC, infinite-turtles commented on modules/nextflow/src/main/resources/nextflow/executor/command-trace.txt
> +    } >> "$trace_file" || >&2 echo "Error: Failed to append to file: $trace_file"
I can see how that would be problematic, bash job groups are a bit obscure anyway. What if we use a single printf statement; only one command that can fail and the same reduction in the open/write/close syscalls.

2024-12-04 15:36 UTC, jorgee approved these changes

2024-12-09 16:06 UTC, pditommaso approved these changes

2024-12-09 16:06 UTC, merged