Document Fusion compatibility for Oracle storage
nextflow-io/nextflow pull request #5495
Opened 2024-11-11 17:05 UTC by pditommaso

This PR document the Fusion compatibility with Oracle Object storage

2024-11-12 06:14 UTC, jordeu commented on docs/fusion.md
> +nextflow run <YOUR PIPELINE> -work-dir s3://<YOUR BUCKET>/scratch
```suggestion
nextflow run <YOUR_PIPELINE> -work-dir s3://<YOUR_BUCKET>/scratch
```

2024-11-12 06:14 UTC, jordeu commented on docs/fusion.md
> +Replace `<YOUR PIPELINE>` and `<YOUR BUCKET>` with a pipeline script and bucket or your choice, for example:
```suggestion
Replace `<YOUR_PIPELINE>` and `<YOUR_BUCKET>` with a pipeline script and bucket or your choice, for example:
```

2024-11-12 06:14 UTC, jordeu commented on docs/fusion.md
> +Also, replace the region `ca-toronto-1` with the one matching your Oracle deployment.
```suggestion
Also, replace `YOUR_ACCESS_KEY` / `YOUR_SECRET_KEY` with your [Customer Secret Key](https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/managingcredentials.htm#Working2). And `YOUR_BUCKET_NAMESPACE` / `YOUR_REGION` with the namespace and region of your bucket.
```

2024-11-12 06:14 UTC, jordeu commented on docs/fusion.md
> +Fusion file system and Nextflow can be used with [Oracle Object Storage](https://www.oracle.com/es/cloud/storage/object-storage/)
```suggestion
Fusion file system and Nextflow can be used with [Oracle Object Storage](https://www.oracle.com/cloud/storage/object-storage/)
```

2024-11-12 07:57 UTC, christopher-hakkaart requested changes
Added some small language suggestions. Please check for meaning.

2024-11-12 07:57 UTC, christopher-hakkaart commented on docs/fusion.md
> +This configuration requires the use of Docker (or similar container engine) for the execution of your pipeline tasks.
```suggestion
This configuration requires the execution of your pipeline tasks using Docker or a similar container engine.
```

2024-11-12 07:57 UTC, christopher-hakkaart commented on docs/fusion.md
> +relying on the S3-like API compatibility provided by Oracle storage.
```suggestion
They rely on the S3-like API compatibility provided by Oracle storage.
```

2024-11-12 07:57 UTC, christopher-hakkaart commented on docs/fusion.md
> +The following configuration should be added in your Nextflow configuration file:
```suggestion
The following should be included in your Nextflow configuration file:
```

2024-11-12 07:57 UTC, christopher-hakkaart commented on docs/fusion.md
> +This option should only be used for development purposes.
```suggestion
The `fusion.exportStorageCredentials` option leaks the Oracle credentials to the Nextflow task launcher script and should only be used for development purposes.
```

2024-11-13 03:11 UTC, bentsherman commented on docs/fusion.md
> +
```suggestion
:::

```

2024-11-13 09:04 UTC, merged