Fix bugs with workflow outputs
nextflow-io/nextflow pull request #5502
Opened 2024-11-13 18:46 UTC by bentsherman

TODO:
- [x] Fix #5460
- [x] Fix #5465
- [x] Fix #5476 
- [x] Fix #5480
- [x] Fix #5543
- [x] Update unit tests, e2e tests where appropriate

2024-12-11 17:47 UTC, bentsherman commented
Tests are failing due to Wave?

```
~ Test 'fusion-symlink.nf' run failed
   + '[' -z *** ']'
   + echo initial run
   initial run
   + /home/runner/work/nextflow/nextflow/nextflow -q run ../../fusion-symlink.nf -c .config
   ERROR ~ Error executing process > 'CREATE'
   
   Caused by:
     Process `CREATE` terminated with an error exit status (125)
   
   
   Command executed:
   
     echo HELLO > data.txt
   
   Command exit status:
     125
   
   Command output:
     (empty)
   
   Command error:
     Unable to find image 'wave.seqera.io/wt/e7b9795c2b58/nextflow/tests:latest' locally
     latest: Pulling from wt/e7b9795c2b58/nextflow/tests
     a3ed95caeb02: Already exists
     1b3e7701db96: Already exists
     a3ed95caeb02: Already exists
     a3ed95caeb02: Already exists
     486f7ff2dd95: Already exists
     009b1e9adc43: Already exists
     5ca4cba2c0a3: Already exists
     2997c9ef2ef5: Already exists
     a3ed95caeb02: Already exists
     a3ed95caeb02: Already exists
     a3ed95caeb02: Already exists
     140836dbc286: Already exists
     eed831c78eec: Already exists
     ac6d42ea81bb: Already exists
     f9510fa3a08f: Already exists
     3dca4ae9f36c: Already exists
     a3ed95caeb02: Already exists
     ceb5650fa213: Pulling fs layer
     dd97694ce7a4: Pulling fs layer
     ceb5650fa213: Verifying Checksum
     ceb5650fa213: Download complete
     ceb5650fa213: Pull complete
     dd97694ce7a4: Verifying Checksum
     docker: filesystem layer verification failed for digest sha256:dd97694ce7a42d826212b59d13df70a643c0192533becd68d9e867f88297c996.
     See 'docker run --help'.
   
   Work dir:
     s3://nextflow-ci/work/89/87e1d9b4c45dedc5006c8f69003[733](https://github.com/nextflow-io/nextflow/actions/runs/12281095140/job/34269672962?pr=5502#step:5:734)
   
   Container:
     wave.seqera.io/wt/e7b9795c2b58/nextflow/tests:latest
```

2024-12-11 17:50 UTC, pditommaso commented
I think it's a Fusion issue @alberto-miranda

2024-12-13 12:21 UTC, christopher-hakkaart commented on docs/workflow.md
> +This example will produce the following index file.
```suggestion
This example will produce the following index file:
```

2025-01-31 12:04 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/extension/PublishOp.groovy
> +            return (targetDirOrClosure.call(path.getName()) as Path).normalize().toUriString()
It would always be better to use `FileHelper.asPath` over `as Path`. Even if it's doing be same under the hood, it would allow us to better keep where this conversion is done.

2025-01-31 12:18 UTC, pditommaso requested changes
I some concerns in this PR both in terms of the complexity introduces by the need for dynamic resolution of closures and String/Path conversions that makes very hard to understand, and even more in the complexity of the resulting pipeline code, for example: 

https://github.com/nextflow-io/nextflow/pull/5502/files#diff-fd4cbeab566b734cd6e0070be77477ff1e70bc1374d4734ca01882273c0e468dR92-R105

One goal of this effort is to provide a more declarative model and less programmatic oriented. I feel this brings back the chaos of `saveAs` closures in the current `publishDir`

2025-01-31 16:47 UTC, bentsherman commented on modules/nextflow/src/main/groovy/nextflow/extension/PublishOp.groovy
> +            return (targetDirOrClosure.call(path.getName()) as Path).normalize().toUriString()
Agreed

2025-01-31 16:55 UTC, bentsherman commented on tests/output-dsl.nf
> +    }
@pditommaso regarding your main comment

The purpose of the dynamic path directive is to map a data structure, like a record, to a directory tree, so that the directory structure can be independent of the index file structure. This decoupling is crucial.

I agree that it is ugly. I would like to find a more declarative syntax for this that is sufficiently flexible. I have a few ideas cooking. But this nested closure is the way to do it in the second preview. So right now the goal is to fix the bugs so that it behaves as intended. The sooner we merge these fixes, the sooner I can start working on a third preview / final version.

2025-02-06 16:20 UTC, pditommaso commented on tests/output-dsl.nf
> +    }
Still struggling my head about this snipper. If i'm understanding correctly `sample` is a map holding a the `id` and other file paths. I guess the closure in then invoked on all map entries that are Path. Is that correct?

2025-02-06 16:41 UTC, bentsherman commented on tests/output-dsl.nf
> +    }
yes

2025-02-06 16:45 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/extension/PublishOp.groovy
> +            final normalized = normalizePaths(record, targetDirOrClosure)
Ok, it has not been introduced in this PR, this always though this is not scalable with a large number of files. It should be taken in consideration an stream like approach before it's released as stable e.g. [here](https://github.com/nextflow-io/nextflow/blob/fix-workflow-outputs/modules/nextflow/src/main/groovy/nextflow/cache/CacheDB.groovy#L50-L50)

2025-02-06 16:52 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/extension/PublishOp.groovy
> +    private Closure dynamicPath
Maybe `dynamicResolver` or  `pathResolver` or just `resolver` is not explicit

2025-02-06 17:08 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/extension/PublishOp.groovy
>      }
This become very "dense". Adding a javadoc and some comments explaining the logic of different branches would help preventing future headaches

2025-02-06 17:12 UTC, pditommaso commented on modules/nextflow/src/main/groovy/nextflow/extension/PublishOp.groovy
>      }
Also wonder why returning a string instead of `Path` the underlying operation will not require converting again to a `Path`?

2025-02-06 19:38 UTC, christopher-hakkaart commented on docs/workflow.md
> +The output block can be omitted if you are satisfied with the default behavior. However, as a best practice you should declare each output in the output block, even if you don't need to customize the
```suggestion
The output block can be omitted if you are satisfied with the default behavior. However, as a best practice, you should declare each output in the output block, even if you don't need to customize the publish path or create any index files.
```

2025-02-06 19:40 UTC, bentsherman commented on tests/output-dsl.nf
> +    }
Another idea based on our discussion today:

```groovy
    path { sample ->
      sample.fastqc >> 'log/'
      sample.bam >> 'align/'
      sample.bai >> 'align/'
      sample.quant >> "quant/${sample.id}"
    }
```

More like a builder DSL, but still requires a closure to access the record members.

2025-02-06 19:52 UTC, bentsherman commented on modules/nextflow/src/main/groovy/nextflow/extension/PublishOp.groovy
> +            final normalized = normalizePaths(record, targetDirOrClosure)
Good point, I will address this in a follow-up PR

2025-02-06 19:55 UTC, bentsherman commented on modules/nextflow/src/main/groovy/nextflow/extension/PublishOp.groovy
> +    private Closure dynamicPath
Good point, I was struggling to find a good name for it

2025-02-06 21:19 UTC, bentsherman commented on modules/nextflow/src/main/groovy/nextflow/extension/PublishOp.groovy
>      }
Somehow I managed to convert a path to string and back to path twice in this function 😅 

I think I changed to return string to ensure that paths were serialized correctly. Taking a second look, I see that the json writer already handles this and the csv writer just needed a bit of extra logic to do the same.

Between those simplifications and some extra comments, hopefully the code is much easier to understand now

2025-02-10 17:33 UTC, merged