Docs: Improve Conda docs - PyPI + lock files
nextflow-io/nextflow pull request #5531
Opened 2024-11-21 11:48 UTC by ewels

* Add docs about Conda lock files
* Create new headings specifically for PyPI, text files and lock files
* Add mention of ability to use PyPI packages to the Wave docs, with link

2024-11-21 12:18 UTC, christopher-hakkaart requested changes

2024-11-21 12:18 UTC, christopher-hakkaart commented on docs/conda.md
> +It is possible to provide the dependencies using a plain text file, just listing each package name as a separate line. For example:
```suggestion
It is possible to provide dependencies by listing each package name as a separate line in a plain text file. For example:
```

2024-11-21 12:18 UTC, christopher-hakkaart commented on docs/conda.md
> +They can also be downloaded from Wave build pages.
```suggestion
Conda lock files can also be downloaded from Wave build pages.
```

2024-11-21 12:18 UTC, christopher-hakkaart commented on docs/conda.md
> +These files include the every package, including dependencies. As such, no conda environment resolution step is needed. This is faster and also better for reproducibility between runs.
```suggestion
These files include every package and their dependencies. As such, no Conda environment resolution step is needed. This is faster and more reproducible.
```

2024-11-21 12:18 UTC, christopher-hakkaart commented on docs/conda.md
> +These are generated from existing conda environements using the following command:
```suggestion
These are generated from existing Conda environments using the following command:
```

2024-11-21 12:18 UTC, christopher-hakkaart commented on docs/conda.md
> +The files contain package URLs and optionally also a md5hash for each download to confirm identity:
```suggestion
The files contain package URLs and an optional md5hash for each download to confirm identity:
```

2024-11-21 12:18 UTC, christopher-hakkaart commented on docs/wave.md
> +Packages from the [Python Package Index](https://pypi.org/) can also be used by using a Conda `environment.yml` file - see the documentation about {ref}`Conda and PyPI <conda-pypi>` for details.
```suggestion
Packages from the [Python Package Index](https://pypi.org/) can also be added to a Conda `environment.yml` file. See {ref}`Conda and PyPI <conda-pypi>` for more information.
```

2024-11-22 16:24 UTC, pditommaso commented on docs/conda.md
> +Conda environment files can also be used to install Python packages from the [PyPI repository](https://pypi.org/)), through the `pip` package manager (which must also be explicitly listed as a requir
```suggestion
Conda environment files can also be used to install Python packages from the [PyPI repository](https://pypi.org/), through the `pip` package manager (which must also be explicitly listed as a required package):
```

2024-11-22 16:26 UTC, pditommaso commented on docs/conda.md
> +Conda lock files can also be downloaded from Wave build pages.
```suggestion
Conda lock files can also be downloaded from [Wave](https://seqera.io/wave/) build pages.
```

2024-11-22 16:32 UTC, pditommaso approved these changes
well done

2024-11-22 16:32 UTC, merged